name: Merge develop and set up Python
description: 'Merge develop into current branch, and set up Python'
outputs:
  WORKFLOW_STATUS:
    description: 'The status of the workflow. Can be "success" or "failure".'
    value: ${{ steps.merge_develop_and_setup_python.outputs.WORKFLOW_STATUS }}

runs:
  using: composite
  steps:
    - name: Merge develop branch into the current branch
      uses: ./.github/actions/merge
    - name: Setup Python 3.9.20 with pip cache
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.20'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: |
          requirements.in
          requirements.txt
          requirements_dev.in
          requirements_dev.txt
