name: Checkout repo and set up Python
description: 'Check out the Oppia repo, set up Python, and merge develop into current branch'
outputs:
  WORKFLOW_STATUS:
    description: 'The status of the workflow. Can be "success" or "failure".'
    value: ${{ steps.checkout_repo_and_setup_python.outputs.WORKFLOW_STATUS }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Merge develop branch into the current branch
      uses: ./.github/actions/merge
    - name: Setup Python 3.9.20 with pip cache
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.20'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: |
          requirements.in
          requirements.txt
          requirements_dev.in
          requirements_dev.txt
